### ISSUE TITLE
Error after deno upgrade to 1.21

### ISSUE THREAD

**Issue by jacorall** [nhttp/nhttp#6]
Getting the following error after upgrading deno to 1.21:
```
TS2339 [ERROR]: Property 'serveHttp' does not exist on type 'typeof Deno'.
      const httpConn = Deno.serveHttp(conn);
                            ~~~~~~~~~
    at https://deno.land/x/nhttp@1.1.11/src/nhttp.ts:315:29
```

**Comment by herudi** [comment]
I tested in my PC it's ok fine. or maybe need `--reload`.

Example :
```bash
deno run -A --reload myfile.ts
```

**Comment by jacorall** [comment]
After upgrading deno to 1.20.0, I use the following when executing may app:
```
deno run -A --reload app.js
```
Then get the error:
```
TS2339 [ERROR]: Property 'serveHttp' does not exist on type 'typeof Deno'.
      const httpConn = Deno.serveHttp(conn);
                            ~~~~~~~~~
    at https://deno.land/x/nhttp@1.1.11/src/nhttp.ts:315:29
```
Part of the code looks like this:
```
import { NHttp, Router } from 'https://deno.land/x/nhttp/mod.ts';
import staticFiles from 'https://deno.land/x/static_files/mod.ts';

const app = new NHttp();
app.use(staticFiles('public'));

 app.listen({ port: 3000, alpnProtocols: ['h2', 'http/1.1'] }, () => {
   console.log('> Running on port 3000');
 });
```
When I downgrade to an older version of deno, it works fine again:
```
deno upgrade --version 1.20.6
```

**Comment by jacorall** [comment]
I upgraded deno to version 1.21.0 using:
```
deno upgrade --version 1.21.0
```

**Comment by herudi** [comment]
weird,, on my PC it runs normally with the latest version 1.21.0. try add `--no-check` flag. and please use version in deps.

```ts
import { NHttp, Router } from 'https://deno.land/x/nhttp@1.1.11/mod.ts';
import staticFiles from 'https://deno.land/x/static_files@1.1.6/mod.ts';
```

Run again :
```bash
deno run -A --no-check app.js
```

**Comment by jacorall** [comment]
When I run it on deno 1.21.0 with the --no-check, it works, but without it, I get the same error.

**Comment by jacorall** [comment]
FYI: I also use the xhr module in my app, and it also gives me an error, when I don't use the --no-check:
```
error: TS2339 [ERROR]: Property 'location' does not exist on type 'Window & typeof globalThis'.
        base = window.location.toString();
                      ~~~~~~~~
    at https://deno.land/x/xhr@0.1.0/mod.ts:499:2
```

**Comment by herudi** [comment]
Possible all module error without `--no-check` in your PC. this bug not related to nhttp. agree ?

**Comment by jacorall** [comment]
I will use it now with the --no-check.  I did a clean install of Ubuntu 20.04 LTS on a VM to test it.  Still does the same.  Perhaps some problem with new version of deno.

**Comment by herudi** [comment]
i don't know, but on my PC with 1.21.0 it works normally even without --no-check. I will close this. thanks for creating the issue.
